{
  lib,
  config,
  kehvatsu,
  ...
}:
let
  cfg = config.custom.providers;
  textMimes = [
    "text/x-sagemath"
    "text/x-python3"
    "text/x-python"
    "text/x-python3"
    "text/x-python"
    "text/x-python3"
    "text/x-python"
    "text/x-ldif"
    "text/x-systemd-unit"
    "text/x-ms-regedit"
    "text/x-objcsrc"
    "text/x-matlab"
    "text/x-r-doc"
    "text/x-r-doc"
    "text/x-adasrc"
    "text/x-scons"
    "text/x-reject"
    "text/x-vhdl"
    "text/x-pascal"
    "text/x-credits"
    "text/x-r-source"
    "text/x-r-source"
    "text/vbscript"
    "text/spreadsheet"
    "text/x-r-presentation"
    "text/x-r-presentation"
    "text/x-texinfo"
    "text/x-ocl"
    "text/x-systemd-unit"
    "text/x-verilog"
    "text/x-lilypond"
    "text/x-gherkin"
    "text/x-groovy"
    "text/vnd.wap.wmlscript"
    "text/x-elixir"
    "text/x-scss"
    "text/rust"
    "text/x-copying"
    "text/vnd.rn-realtext"
    "text/x-gettext-translation-template"
    "text/x-go"
    "text/markdown"
    "text/x-meson"
    "text/x-troff-me"
    "text/x-r-profile"
    "text/x-genie"
    "text/x-ooc"
    "text/vcard"
    "text/spreadsheet"
    "text/vnd.familysearch.gedcom"
    "text/vnd.graphviz"
    "text/x-makefile"
    "text/x-systemd-unit"
    "text/x-ocaml"
    "text/x-gcode-gx"
    "text/x-groovy"
    "text/x-objc++src"
    "text/x-troff-mm"
    "text/x-modelica"
    "text/x-scala"
    "text/x-tex"
    "text/x-r-html"
    "text/x-r-html"
    "text/x-systemd-unit"
    "text/x-common-lisp"
    "text/x-troff-ms"
    "text/plain"
    "text/calendar"
    "text/vcard"
    "text/x-cmake"
    "text/x-maven+xml"
    "text/x-c++src"
    "text/x-makefile"
    "text/vtt"
    "text/x-nim"
    "text/x-c++hdr"
    "text/x-c++hdr"
    "text/sgml"
    "text/x-scheme"
    "text/x-dsl"
    "text/x-authors"
    "text/vnd.sun.j2me.app-descriptor"
    "text/vcard"
    "text/x-apt-sources-list"
    "text/x-svsrc"
    "text/x-install"
    "text/x-c++hdr"
    "text/x-blueprint"
    "text/x-r-markdown"
    "text/x-r-markdown"
    "text/x-haskell"
    "text/troff"
    "text/tab-separated-values"
    "text/x-sass"
    "text/x-meson"
    "text/x-eiffel"
    "text/x-gradle"
    "text/x-c++src"
    "text/x-ssa"
    "text/x-fortran"
    "text/vcard"
    "text/x-literate-haskell"
    "text/x-c++src"
    "text/x-mup"
    "text/x-basic"
    "text/x-vala"
    "text/x-systemd-unit"
    "text/vnd.familysearch.gedcom"
    "text/x-vhdl"
    "text/x-systemd-unit"
    "text/x-uil"
    "text/x-typst"
    "text/x-cobol"
    "text/x-fortran"
    "text/x-opencl-src"
    "text/x-moc"
    "text/x-setext"
    "text/x-devicetree-binary"
    "text/x-iptables"
    "text/x-fortran"
    "text/x-mof"
    "text/tcl"
    "text/x-r-markdown"
    "text/x-r-markdown"
    "text/x-xslfo"
    "text/x-cmake"
    "text/x-crystal"
    "text/tcl"
    "text/x-csharp"
    "text/x-dcl"
    "text/css"
    "text/x-dbus-service"
    "text/x-systemd-unit"
    "text/troff"
    "text/turtle"
    "text/vnd.trolltech.linguist"
    "text/csv"
    "text/x-google-video-pointer"
    "text/x-kaitai-struct"
    "text/x-uuencode"
    "text/sgml"
    "text/jscript.encode"
    "text/x-devicetree-source"
    "text/x-groovy"
    "text/x-tex"
    "text/x-tex"
    "text/x-mup"
    "text/javascript"
    "text/x-log"
    "text/x-quarto-markdown"
    "text/x-texinfo"
    "text/x-iMelody"
    "text/x-maven+xml"
    "text/x-dsrc"
    "text/x-scheme"
    "text/x-rst"
    "text/x-lua"
    "text/x-qml"
    "text/javascript"
    "text/plain"
    "text/x-vala"
    "text/vnd.graphviz"
    "text/x-c++hdr"
    "text/x-common-lisp"
    "text/x-pascal"
    "text/x-mpl2"
    "text/x-r-sweave"
    "text/x-r-sweave"
    "text/x-twig"
    "text/x-cobol"
    "text/julia"
    "text/csv-schema"
    "text/x-tex"
    "text/x-iMelody"
    "text/x-patch"
    "text/javascript"
    "text/markdown"
    "text/x-ssa"
    "text/x-bibtex"
    "text/x-xmi"
    "text/x-r-sweave"
    "text/x-r-sweave"
    "text/org"
    "text/plain"
    "text/x-microdvd"
    "text/x-mpsub"
    "text/x-subviewer"
    "text/x-makefile"
    "text/x-scons"
    "text/x-vb"
    "text/x-gettext-translation"
    "text/x-nfo"
    "text/x-c++hdr"
    "text/x-emacs-lisp"
    "text/x-txt2tags"
    "text/x-changelog"
    "text/x-systemd-unit"
    "text/richtext"
    "text/x-python3"
    "text/x-scala"
    "text/x-c++src"
    "text/x-scons"
    "text/x-tex"
    "text/x-devicetree-source"
    "text/x-elixir"
    "text/x-nimscript"
    "text/x-systemd-unit"
    "text/vnd.wap.wml"
    "text/calendar"
    "text/x-tex"
    "text/x-common-lisp"
    "text/x-patch"
    "text/x-kotlin"
    "text/x-opml+xml"
    "text/x-mrml"
    "text/x-tex"
    "text/x-rpm-spec"
    "text/x-groovy"
    "text/markdown"
    "text/x-ocaml"
    "text/x-c++src"
    "text/cache-manifest"
    "text/x-nimscript"
    "text/x-component"
    "text/x-java"
    "text/x-svhdr"
    "text/x-r-history"
    "text/x-systemd-unit"
    "text/x-qml"
    "text/x-qml"
    "text/x.gcode"
    "text/x-adasrc"
    "text/x-xslfo"
    "text/x-makefile"
    "text/x-common-lisp"
    "text/x-csrc"
    "text/x-systemd-unit"
    "text/x-dsrc"
    "text/vbscript.encode"
    "text/x-eiffel"
    "text/x-fortran"
    "text/x-mrml"
    "text/x-erlang"
    "text/x-idl"
    "text/x-chdr"
    "text/vnd.senx.warpscript"
    "text/troff"
    "text/x-makefile"
    "text/x-todo-txt"
    "text/x-readme"
  ];
in
{
  options.custom.providers = kehvatsu.options.custom.providers;

  config = {
    xdg.configFile."mimeapps.list".force = true;
    xdg.mime.enable = true;
    xdg.mimeApps = {
      enable = true;
      defaultApplications = lib.genAttrs textMimes (_: cfg.editor.desktop) // {
        "text/html" = cfg.browser.desktop;
        "x-scheme-handler/http" = cfg.browser.desktop;
        "x-scheme-handler/https" = cfg.browser.desktop;

        "application/json" = cfg.editor.desktop;
        "text/markdown" = cfg.editor.desktop;

        "inode/directory" = cfg.fileManager.desktop;

        "image/*" = cfg.imageViewer.desktop;
        "video/*" = cfg.videoPlayer.desktop;

        "application/pdf" = cfg.pdfViewer.desktop;
      };
    };

    xdg.terminal-exec = {
      enable = true;
      settings.default = [ cfg.terminal.desktop ];
    };
    home.sessionVariables = {
      TERMINAL = cfg.terminal.program;
      EDITOR = cfg.editor.program;
      VISUAL = cfg.editor.program;
    };
  };
}
