keys:
  - &desktop-host age1426exnrvr5fmalhhh0vgajar2k92xhr0nshhgnqhpycvcgautdlsvqedq6
  - &desktop-langsjo age1gwpmfgjkhcwp8nlaljxfdr3pp0np02656eq9kjpmtt0u3al99smswuj8lp
  - &kehvatsu-host age19w9wmdra2frq9f7hv0883xprnzzgfulv29fru25wgyfgwuxt6yjqnsvg04
  - &kehvatsu-langsjo age13y3kv3ees7xx8fkerfcvjk0sjaz0n6f5pztu6ply4gl2tfhdjulstj4d2u
  - &gorilla-host age1urqqvjhryzm742tmt6yrzxp6g7h45r4mnz4fdfx0r4d7ygspd5uqelpzh2

creation_rules:
  - path_regex: modules/secrets/[^/]+$
    key_groups:
      - age:
          - *desktop-langsjo
          - *desktop-host
          - *kehvatsu-langsjo
          - *kehvatsu-host
          - *gorilla-host
  - path_regex: modules/secrets/kehvatsu/[^/]+$
    key_groups:
      - age:
          - *kehvatsu-langsjo
          - *kehvatsu-host

  - path_regex: modules/secrets/gorilla/[^/]+$
    key_groups:
      - age:
          - *kehvatsu-langsjo
          - *gorilla-host
