restic-server-passwd: ENC[AES256_GCM,data:svX/zgZ0aSRbbeBjta0zbP8FRoLPvvx5YkF45X54Ecutc//HTbP26Opj28M=,iv:YhnCUkGIVxMFcePQ6BDhyXSLyBaQabIP5GTWQyr5Aw8=,tag:FQoNz9RI4km+gkkF8g/uIg==,type:str]
restic-encryption-passwd: ENC[AES256_GCM,data:vxZ3U95Ef0jhKUu2hhIfn+C25Xb6AO1phWd7JPaYrGVsAAlmkCc92ubHO8Y=,iv:5fV+cFsqcjPLbava6ibO2wvqbhu7qdkSgwcLTdkKofM=,tag:wKkN8IIMlzdsAMkJsfPKfg==,type:str]
sops:
    age:
        - recipient: age13y3kv3ees7xx8fkerfcvjk0sjaz0n6f5pztu6ply4gl2tfhdjulstj4d2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN0czQzBUdzR1SWpyenRH
            b3dZcWUraThxQUJTRjBOQ1FGUG5odkRKK0E0CnNYb2NNSUZ6VFJZeFBNZlVJR2RK
            QUxzRmxLenMza0RPQXprWms1cUovMFEKLS0tIFk0eE9sWU9JVWRlbkxDczVQQktl
            TVgxeDZlZlhqTG4rN016ZnFsN3RML28KkNKF8rZDOmqpIl5NCUU5pktKzEJ24hSZ
            I1H2FPjwHuK7kz0MHJwqFdV/lvpQzqd2jD006b4UkhfhyniCPoZh+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19w9wmdra2frq9f7hv0883xprnzzgfulv29fru25wgyfgwuxt6yjqnsvg04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYzhZL2o5ZDdyTVFicUQ5
            YWc5anVHOFNpc0xoRGluYjB3SnJnamFtaW5JCllCWEJKWEVZc3BoQUpIVVZ1NXhs
            QXpYNGs2dUNyeVFqL2lmTjdGZkJPVGsKLS0tIDZBdkRrYVQ0enNOWFp4ZDFaV0hV
            T3NLUklEbDl6QXNXQVJqL3FiVE9PaXMKDZ37RF7M/teln2jGfH6hq9deOpfPlJ37
            rlx0jyWaWUUTuDMEYRblF02qndJRsFjcNLRK5I8lroyKo+elOskY1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T18:44:24Z"
    mac: ENC[AES256_GCM,data:doeZDfX2qTLiGyLukFVVPcI9IJjyB7qgBZXWGivmM/T5P9kAtx8449Bj+zDGILfSIJiifkQ2f+zACSewTKsLeFMErZE/MfN4nmviUnBe5NNBaxidsUs8Z+OzssyyTUaqidXONbSfaihkun6sIY50gMXak/QYLGGz75yY9oyT3dg=,iv:18pHThjakfUpVPyZBFPAx+iptlChih3+gFLwZwNgauc=,tag:cd99Yzqq51pvkFAi2IVjGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
