restic-server-passwd: ENC[AES256_GCM,data:svX/zgZ0aSRbbeBjta0zbP8FRoLPvvx5YkF45X54Ecutc//HTbP26Opj28M=,iv:YhnCUkGIVxMFcePQ6BDhyXSLyBaQabIP5GTWQyr5Aw8=,tag:FQoNz9RI4km+gkkF8g/uIg==,type:str]
restic-encryption-passwd: ENC[AES256_GCM,data:vxZ3U95Ef0jhKUu2hhIfn+C25Xb6AO1phWd7JPaYrGVsAAlmkCc92ubHO8Y=,iv:5fV+cFsqcjPLbava6ibO2wvqbhu7qdkSgwcLTdkKofM=,tag:wKkN8IIMlzdsAMkJsfPKfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEgvSWtkUSBBNHQxbCtO
            Rzgxczg3clRaRy9KUFZ3dzV5L2ZvOFVOWnRUdjhPQTcrc1M3ZApzcERlZWFRMUdP
            bmZCTkkrU3ZMNWY3QUpGMmdId01JQnJCZGhSUC9ZakZFCi0tLSBqWmRxTnBPSjVR
            ZUZVZkZoZE1TMDgrbG5WZHhtd0tDejJqbFZ4ZzVSQnBFCscCWG+ezppf9FD4UQxn
            QGDR7pHj6OZvEw5P043jJYR3V2FjGiSkEImC3WEaVYDdWYBYG/jJtIGDSTxvHafk
            v/o=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q0garr0k6y39vc05kyt5p858zrunk7lupg926l3rmv6any7as3gduvgu6v5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNGlFNCsvdStQR21nTk9a
            QUxpeUlGWFJ1bXZoWGIrWXkvTGtpOTY3VFUwCm93dUVXUjdSdkc1dlhBc2NDUFNm
            M2pKNW1JMktMS2ZkLzR6UnBqd3ZxYnMKLS0tIE9aTHVqQitVUEZaUGVZaFU1TWNv
            VDFMNVBXRExRN1lvVmNEUHdzajIzRmMK22wtvWViV7z//d3F79TN/DZeu6g88o9n
            W+k/QfLf0kcoeU5XUE3qlVZUQ648ouuhQO9+XFzA9fkij7ABwfOdmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19w9wmdra2frq9f7hv0883xprnzzgfulv29fru25wgyfgwuxt6yjqnsvg04
    lastmodified: "2026-04-09T18:44:24Z"
    mac: ENC[AES256_GCM,data:doeZDfX2qTLiGyLukFVVPcI9IJjyB7qgBZXWGivmM/T5P9kAtx8449Bj+zDGILfSIJiifkQ2f+zACSewTKsLeFMErZE/MfN4nmviUnBe5NNBaxidsUs8Z+OzssyyTUaqidXONbSfaihkun6sIY50gMXak/QYLGGz75yY9oyT3dg=,iv:18pHThjakfUpVPyZBFPAx+iptlChih3+gFLwZwNgauc=,tag:cd99Yzqq51pvkFAi2IVjGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
