eduroam/id: ENC[AES256_GCM,data:2TpXVgFIauZkted0/gTWSLH9Q5o=,iv:AlxJApOukLttz2j51SqRhsL2nCnolVIzxOrJ4Dk3jR0=,tag:Y5FA0KzYcVaIqkRWDDqLig==,type:str]
eduroam/pass: ENC[AES256_GCM,data:nmBpU83R/AcNUEqFNb/bhzSV7Oo=,iv:NCbzx7CuZTO7ERNKXv3CybTtUXEfU2DWv5x8ZAAdp+s=,tag:QEwzdhafCGsgzg8N28AOLw==,type:str]
sops:
    age:
        - recipient: age1yezgssun7zpwt9g629dwjp8q3wddc8xp5k990ms7jtv6xku9yunq802pze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTlVzb0hCR3ZhTlRZVzd2
            a2tVRURBZVdnV1BETGhNYzNIWVJZQzV6aVg4Ck1hZHdqY1dCODJ5RUNNeE95RXky
            bnRTMG55aDdrOExuM2RVSUZ6WmcwYVUKLS0tIGZtNjNRTlVaSVJZV08ydDNYV20w
            MWN3RUxqZWM1UDNZbFJXVGFma0hrQzQK7gbzirlru0w/TLQtRXVogrJIRUfKAIHD
            3NFm1xFqq4Xuk4EOO2YKdjjJb1NunzGQwZ8Ein70UvnB8Bt0lWurmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j3n82enjgvacg7dhjhnfwhmvc76ce6l8wmg5w5kkx8f6f8qyt9cs3e6s7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Rmd5Yk5HOVVna3A5Ym5S
            aGw2eDNWMExMbkk1cUZZSnVLUnExSUxqcWlBCllZdkR6UEZGZjk3bkk0M3BtQ25i
            VjFBV05tK0x3MG5VczFLZm9peTNtVFkKLS0tIFp0NHgvSlFCUzVPWVdZRjZkZXMy
            U2pwOVVWOE5JOFlyVjBNWW4wanptQkEK7dplz9wogsK8iflWYEnngzKwO0hkTQZB
            eNRPUtWhOG9iMrCQQQVixurIdiaXz/RG79pQqMuJbjQtWul/vvoXDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gwpmfgjkhcwp8nlaljxfdr3pp0np02656eq9kjpmtt0u3al99smswuj8lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeUtFd0VIQkZMRkppcXpZ
            VWpIL1ZRRWlXK1kvUHZCcXFGNi9FcmdOakV3ClZ5YmJ2U0JJeC9FMFNMdFVBQ1hO
            bjNFbUxKS2M2endtZENpTFBrcGU5SmcKLS0tIExGWndURHFRWVVlVEhZRzhhbmlk
            OXNQTk1lV3puZUNjeXduZGR5TC9DNzAK50km6dOsQTLIchB+HWE5mhZB2RH+TK9z
            DHCw7LovQzsp4CdvN0sJBahLCyRRoIopXeiDpt6Ek4kPz37w/hZcHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19w9wmdra2frq9f7hv0883xprnzzgfulv29fru25wgyfgwuxt6yjqnsvg04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZFJNRWdKUmZHK0JXMWFK
            MldqT3hXQitDTlkrWjcycXRjeGxDNE5sOFhnClJrSHZyQ2l4NzlSWnFiNytmTmZN
            RWJXS0YvOTc5Smd2ZWc3SnhxbWpDbmsKLS0tIFhrdTJ1a0VmakU1eFUrMGJ0eWs4
            Si8ySUwvWG8rbWJaT2VvOVNrdHp3amcKtXIpXxozj4h7euHxVCkMpSkv8O9ouyHZ
            3ftzuv30kxO6flNW+gmEutQeUZyjSN4vI7UziwCitWIwZ4D+YdpLNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T17:37:30Z"
    mac: ENC[AES256_GCM,data:LVnJCpyZxBQMEmnxx+nrjTslotP2lCTYvFxhb1Pn86HseebTXl4g5IiHbwaU/qjTUh7/wKdGaHCU1LCMZi3/hdlw2LjYh12phJixup5KlTywdzdZHoSCf4aJTxIgpd5JkSAqEsp9Tv9Dz7pZI6X4DBEXwxYNVWPZV8ryAI/qlFQ=,iv:2RDUA1UL/9uiqdtCC9A48G25xjqieiHerGJgT/TtOg8=,tag:C3AAQXeF5ZFotMn67mMkxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
