users:
    hashed-root-pass: ENC[AES256_GCM,data:ZVcYKK1RpPtIn8ewuKUHI2LtknxnkC8G4Hiawg34XmxbpPOWhgmA9i9S304mVng9qLeYYmWyLu9leAzRJ8nim5jSnXGsakvO1w==,iv:1z1FlpL2ix7RJXpg2kTLkI0VKeg3Bl4cY5ScL48O6Q8=,tag:sTHkTxWKDcQuVA3ppCIKfw==,type:str]
    hashed-user-pass: ENC[AES256_GCM,data:dYkXzNgHT6Xq/pJE06Lz1222tTFcclKhWAjI8ZmhTBggaFmIc00XRwednCjc0GFU/vJdQGv1FC10hmJdODaAMHQsWV6cvGCRsw==,iv:KGYmJM2rg7tSyKhYGSrFIkfU1xA5wyib58jYMlMe43I=,tag:GLsRcH8QX+XHKSH99O4lVA==,type:str]
eduroam:
    id: ENC[AES256_GCM,data:7c7VPT10cIJXlTH3aEkC4A3sBD4=,iv:snuGbgIsPSTsI4IRulqnOmEu0p17OeO+zCm/s8JoP9g=,tag:KEKUU4lXRZlhlFmUKvy0aQ==,type:str]
    pass: ENC[AES256_GCM,data:nOaEBYssFZp2aw5H3kg=,iv:gFbd2ZlZ2dy2srqjh+AbRSgzJV5GndWHjR0ThAawtJw=,tag:oRqiwnJSNYPtmQvPq5EW1w==,type:str]
zyxel:
    pass: ENC[AES256_GCM,data:pQGQvtOem41CzA==,iv:q9RaHgcCGSnsnfXxCYvD10N5fXG6nZZBHIDlDDKnOl0=,tag:LOMYU7IDU9nHw4dTc1wNxg==,type:str]
github-pat: ENC[AES256_GCM,data:tKNGtRHCaNtvLNfhoml4KxyynZOA5FUtG4bDrK2sfRD1T25f8HA1M3OXi0RNT3YielZRi5O1BMZVAysTZJS2aj8GPZHB42a2P7MgCD7kYrcoJaVlKgLwY0HA0ENF,iv:geJWsDBhtxP4Bt6610bOikA7d+pkerQj9789nyzs2ec=,tag:1IzVN6eAGt57YvEyKkZH3Q==,type:str]
nix-signing-key: ENC[AES256_GCM,data:Y6yKcFdrMCQvcnxkeLQEn7E/51un77LxwpIWVQqT+q6nSlnPNYsmw/xDTzon+4LgKOJCvbtIyBZfeVsvWUzFN+DEPkFrpu1lnQkdcOlDF+rYF/c9EecUVw91blEKQ6ND,iv:SEpr7qxSkJVpusti5+4MZr20aLPMxkQKa/aoH5HIFLw=,tag:ncR/fpNlqfD11d8wa+KiZQ==,type:str]
attic-netrc-file: ENC[AES256_GCM,data:l1liu7ndvqmHpRp8524dySKaE/bdznmGVlAkuY+LABGdtLB5fiXAJmE2S3S/BArddXWUvCGVbPYc6JLiY3TGHK4ffIAJxVZ8dxB+mnP6HJAu22u01KX75kDEVXNE91TaHSLt56meQuxNAHghm3/6Tl0c8QbHLMZTU92cXQ2NFflrEjEWZscMT3kwsPoTJxf+sBdNAk90+12xOpy54D5JXfEP9yKcRMI1B2rHlkBVYMB9qR4fSdAUhSe958ZXQD1np1vY3C2Ym0kkAMBliyu3n6O21t26PU+Uiuq/4zZ1ef16YfUzSr4eTD+nFPIOufCzIQVw8hfvGYXIUmrZ0w8ibE2Zwe+qBFVFmcywDMzXDzEandnpTGMvZbNzHl90BQe7OvKOmTfG6oe60k1Q0BA73lHLhvK16WCMtdL7AWV96xDpM3NKdV0tS4aH4b54ynv6fxmXNvE4LOE0QULcvxjmVIxMiXFQ7HupxOzuZyKIqnyR05hZ2kq1QxBm/LsWoZKNMlWyxJQ370kMHtRKgvUtwuS7dOGeB3bjHGuQPyYEiPFIVhRGap9mPe6UJ+q3I8LF9a6P66M4yp2iN+DEg4rGMNBcZHmYK3XGg/who19nsJc1I/FCDIwZvzpmDaf2/rFHKPYJF41S0t7v/+RJmbd+erPiDTTzb0KSFc/MIti2x1hND+lo/l+5KONJmjkYbttGu4pIoldr3Kx05mHGkco3Mp8A8QWqBYYH7Whcruu9RjlaEl8/jCmM7gNEub8xlZHOkhaQTQ1WFBLInOHbqmVjtOB+TDK7Xoe7Y7IZaJsRL4tEqUJFGXVvklcbLq8FlvpMusXXAk0F+CoEt4Y8uMBY78b+kbOORLQJHemIXM98kg46iGrB5Tj24dDTflOJe28egawS0N0KcRaqnUMhs9VC0EdJDWaiWv+Jte9G061IOW5Bt40foHsQNrBGb6gFSQdfM/ZqN8k/96yrVDIPNHI2Ce0cykcfhtfgDeXYCRaFwXcU5kY2wC5bEvhFngrKAl6N0HMI1kNCV8ky645D9y4gfhFKIzECLky9XOTQd0J3j9pX99wwThZhTdVPc3jgERILa/RJFkFE86GQLvsiVM/aT6H7aItnxHs/btojtvSjBcGxDeA+UHf6O0Q+oHjNPzw5mtdaxEbOtcdk1yGVda1RkV+I8kr/12LKF3DyeXeaQDfT,iv:Mxh1tFnzoTc0JIzSK2f4ussog8fCIm/KPIud3El++Zg=,tag:XN9/EURvzthcb1eZ0hzinQ==,type:str]
sops:
    age:
        - recipient: age1gwpmfgjkhcwp8nlaljxfdr3pp0np02656eq9kjpmtt0u3al99smswuj8lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVW9NbW51dlljTW9paDZV
            Q0hWQ1VMSUFuZk1JdFd6YkN6OWZxTFFPdkhnCis1ZjNXRlVPR1V1MmpIR1Job0tF
            THl2S0Q4M3Y3bkQybi9vUi9KaGx5M1EKLS0tIDN5M0tIQ05RSFFiZHAvSnFlUnFN
            VVh4TndnakZCSjE3Z2JENHdYenRFcFUKbdNZH0BsE/NuhGl+R0DEcwXTmj4vwHie
            AZ9CUO8aT6mmF//BksSuvJ7+2GBVkPeSuyCE6aibuXWIZAJplbSUIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13y3kv3ees7xx8fkerfcvjk0sjaz0n6f5pztu6ply4gl2tfhdjulstj4d2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTHc1TVVBa1VmcVpPTk1n
            VG4xbmRPNWgybjFjd0lMbTRtVnpiUEtzcnhZClpIcmlPT2pSbm5GWm4zZGlzRERy
            RU5qamhWcHVMUnV2VlIvcUd5bUlzQm8KLS0tIE90a2tFY2htT1d5NDVvOERFU3ZO
            RUhnOE1FNkcxWWg0dGVIWE80a0dVVlEKY1/+KET02/+4XhWo93Ww5GPaSt5arCsP
            2BBuny3+Rp9zpc1BncRQ9P+F3FJ7dTJTRzo+qM/t5FqsxZIBh+OVTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19w9wmdra2frq9f7hv0883xprnzzgfulv29fru25wgyfgwuxt6yjqnsvg04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWTZVUi9XcmdwZGhnUFBv
            VUhEWGJIRFNQbVVSOU9yWWJTR1VGOHg0L1ZvClo5MDVuSDlJdlphdDVWK3haVGJM
            QUQ2elVFeGYvMHNhdUtic05GcFliYmsKLS0tIGVJelM3OWwzREZ1bmNFS2RjQ1ZI
            bVdJRWhyS1oxUEI3KzNzRlpmc09QMlkK1En78AnBxU2Lts7v7MLAzrQtYv90GFyR
            1MYOd8jD5GSqtzLiTGuA3MlrnCNML/XqmV7Ye67S62WJuy4raRzQbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1urqqvjhryzm742tmt6yrzxp6g7h45r4mnz4fdfx0r4d7ygspd5uqelpzh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrelh2SzZPaC96NitBT0Iv
            cmY2ZEZreGpKajY3ZVRhbmx6MDVqY3FMWXl3CnhtMlRTbmRyRVJaZXIxU24xRE5j
            TXBBS3JwQmFSWUJRUjVnZGFucG84WVUKLS0tIFR6NjNFNGdia1B6ODRjSkU1VjAx
            VUUzZGhhOWNuTkE3KzBwWkNsazVFbTQKCWlhvswx0IMI0pYhP2ATDJdZgPMOTZAd
            dL7yzBqqQlx5VaN49LPdxQDrP84z4WN6orJq5wSsG2RStZqcmV4Ceg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T02:47:09Z"
    mac: ENC[AES256_GCM,data:MCVZN8IEHK3I+u7lsiUphQQUOzs3ZorZLKDH7ZuniWKHQke+NOq25clgMit3cAKDj9e+Z+4epZiOQr1cY/IyEw/p2TXiD6RRf7MRgU72japv5NkUBqttx9NzQu19BljsAh58AbHEH3mkWFbtofKBrHRbrfAi4zRDRfCAuXbrut4=,iv:QjUHK0BMRSN73Z7TSRxD7X+H2XVjrixGuCSxeChzmmM=,tag:3VbGKwRFsmuSuTNSYcfDIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
