users:
    hashed-root-pass: ENC[AES256_GCM,data:ZVcYKK1RpPtIn8ewuKUHI2LtknxnkC8G4Hiawg34XmxbpPOWhgmA9i9S304mVng9qLeYYmWyLu9leAzRJ8nim5jSnXGsakvO1w==,iv:1z1FlpL2ix7RJXpg2kTLkI0VKeg3Bl4cY5ScL48O6Q8=,tag:sTHkTxWKDcQuVA3ppCIKfw==,type:str]
    hashed-user-pass: ENC[AES256_GCM,data:dYkXzNgHT6Xq/pJE06Lz1222tTFcclKhWAjI8ZmhTBggaFmIc00XRwednCjc0GFU/vJdQGv1FC10hmJdODaAMHQsWV6cvGCRsw==,iv:KGYmJM2rg7tSyKhYGSrFIkfU1xA5wyib58jYMlMe43I=,tag:GLsRcH8QX+XHKSH99O4lVA==,type:str]
eduroam:
    id: ENC[AES256_GCM,data:7c7VPT10cIJXlTH3aEkC4A3sBD4=,iv:snuGbgIsPSTsI4IRulqnOmEu0p17OeO+zCm/s8JoP9g=,tag:KEKUU4lXRZlhlFmUKvy0aQ==,type:str]
    pass: ENC[AES256_GCM,data:nOaEBYssFZp2aw5H3kg=,iv:gFbd2ZlZ2dy2srqjh+AbRSgzJV5GndWHjR0ThAawtJw=,tag:oRqiwnJSNYPtmQvPq5EW1w==,type:str]
zyxel:
    pass: ENC[AES256_GCM,data:pQGQvtOem41CzA==,iv:q9RaHgcCGSnsnfXxCYvD10N5fXG6nZZBHIDlDDKnOl0=,tag:LOMYU7IDU9nHw4dTc1wNxg==,type:str]
github-pat: ENC[AES256_GCM,data:tKNGtRHCaNtvLNfhoml4KxyynZOA5FUtG4bDrK2sfRD1T25f8HA1M3OXi0RNT3YielZRi5O1BMZVAysTZJS2aj8GPZHB42a2P7MgCD7kYrcoJaVlKgLwY0HA0ENF,iv:geJWsDBhtxP4Bt6610bOikA7d+pkerQj9789nyzs2ec=,tag:1IzVN6eAGt57YvEyKkZH3Q==,type:str]
sops:
    age:
        - recipient: age1gwpmfgjkhcwp8nlaljxfdr3pp0np02656eq9kjpmtt0u3al99smswuj8lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVW9NbW51dlljTW9paDZV
            Q0hWQ1VMSUFuZk1JdFd6YkN6OWZxTFFPdkhnCis1ZjNXRlVPR1V1MmpIR1Job0tF
            THl2S0Q4M3Y3bkQybi9vUi9KaGx5M1EKLS0tIDN5M0tIQ05RSFFiZHAvSnFlUnFN
            VVh4TndnakZCSjE3Z2JENHdYenRFcFUKbdNZH0BsE/NuhGl+R0DEcwXTmj4vwHie
            AZ9CUO8aT6mmF//BksSuvJ7+2GBVkPeSuyCE6aibuXWIZAJplbSUIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13y3kv3ees7xx8fkerfcvjk0sjaz0n6f5pztu6ply4gl2tfhdjulstj4d2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTHc1TVVBa1VmcVpPTk1n
            VG4xbmRPNWgybjFjd0lMbTRtVnpiUEtzcnhZClpIcmlPT2pSbm5GWm4zZGlzRERy
            RU5qamhWcHVMUnV2VlIvcUd5bUlzQm8KLS0tIE90a2tFY2htT1d5NDVvOERFU3ZO
            RUhnOE1FNkcxWWg0dGVIWE80a0dVVlEKY1/+KET02/+4XhWo93Ww5GPaSt5arCsP
            2BBuny3+Rp9zpc1BncRQ9P+F3FJ7dTJTRzo+qM/t5FqsxZIBh+OVTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19w9wmdra2frq9f7hv0883xprnzzgfulv29fru25wgyfgwuxt6yjqnsvg04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWTZVUi9XcmdwZGhnUFBv
            VUhEWGJIRFNQbVVSOU9yWWJTR1VGOHg0L1ZvClo5MDVuSDlJdlphdDVWK3haVGJM
            QUQ2elVFeGYvMHNhdUtic05GcFliYmsKLS0tIGVJelM3OWwzREZ1bmNFS2RjQ1ZI
            bVdJRWhyS1oxUEI3KzNzRlpmc09QMlkK1En78AnBxU2Lts7v7MLAzrQtYv90GFyR
            1MYOd8jD5GSqtzLiTGuA3MlrnCNML/XqmV7Ye67S62WJuy4raRzQbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1urqqvjhryzm742tmt6yrzxp6g7h45r4mnz4fdfx0r4d7ygspd5uqelpzh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrelh2SzZPaC96NitBT0Iv
            cmY2ZEZreGpKajY3ZVRhbmx6MDVqY3FMWXl3CnhtMlRTbmRyRVJaZXIxU24xRE5j
            TXBBS3JwQmFSWUJRUjVnZGFucG84WVUKLS0tIFR6NjNFNGdia1B6ODRjSkU1VjAx
            VUUzZGhhOWNuTkE3KzBwWkNsazVFbTQKCWlhvswx0IMI0pYhP2ATDJdZgPMOTZAd
            dL7yzBqqQlx5VaN49LPdxQDrP84z4WN6orJq5wSsG2RStZqcmV4Ceg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T12:07:51Z"
    mac: ENC[AES256_GCM,data:8MvKD0gqMvE6CKkzpjzcOrrE6aFjKH/+T7Kwo48pPjV+qoyFoIkNjndg/+Q2gxZs8fQpFxY8RVfxMVu3ZmIFroBk+gri3Y3VxBMSJcMV6co8hikOWiI8LX8SuivhVVJpME7ENxHSMRAFKTIwgDjJJt5H4JTYjpFkdI3wKKUqUao=,iv:12iOV4Cyv20WiCEhpWMHJHhIAXWunpHj2AZuiiAHOkE=,tag:3RCFbPhGNefmdw5+vsPhnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
