eduroam:
    id: ENC[AES256_GCM,data:7c7VPT10cIJXlTH3aEkC4A3sBD4=,iv:snuGbgIsPSTsI4IRulqnOmEu0p17OeO+zCm/s8JoP9g=,tag:KEKUU4lXRZlhlFmUKvy0aQ==,type:str]
    pass: ENC[AES256_GCM,data:bqXef1WFmBnrOBEtNMyT5X8lubc=,iv:kgcIREZicj+IUprzGUUQ/d/PUsgxiWhg+QZhgadtyFE=,tag:1SIT2XMjJcoiP5uFsAZ12A==,type:str]
sops:
    age:
        - recipient: age1yezgssun7zpwt9g629dwjp8q3wddc8xp5k990ms7jtv6xku9yunq802pze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL2xSNlo2QjBmQlV4ME5K
            SjQvQzl4SnQxcUdnczZ5ZWV0QSs3NWFiMHdjCmZFcW1lRi9BTXMxTmNnVHVTM2Q3
            NHZLaEh6Q2ZYcGV3bWEyemtycHRNSzgKLS0tIDYvMkl0TTRhY0N0RVFvNWg5Ym14
            dGkzbU00SjFmdHhhK0dHbXdSdE00OGcKXWkk3oEYtgnP/PngOAANKys67EDfn/Ce
            PZPuJe/c7qU/bOc1i2IWAGzOaNbD0aLS5RUcz+FZ77TKGzqnBuplVw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j3n82enjgvacg7dhjhnfwhmvc76ce6l8wmg5w5kkx8f6f8qyt9cs3e6s7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYWQwRjAvVUZiZXJmbk5i
            QXA5SEtHNENPdXQvb1FYY0VGZUZSazB1L0NJClVaK042S2ZnNkkzQ1FRUDl1UUVh
            SnYzRVlURnQ3WWNBdjFTdEQ2a251UGsKLS0tIGhQMzZOVHorUnZkc1VaalBsU0xz
            dW1ZajZ0czM2ZEU0MDFLNElsQVdmd0EKbNtYm/AMF9XLUaSR4EAr1/sVr4ShklGL
            v1+JNRimeo9ED9ZUaPWtEzeXxgf1HEDDsBnd+eZcz+DVaqwSl/F8kg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gwpmfgjkhcwp8nlaljxfdr3pp0np02656eq9kjpmtt0u3al99smswuj8lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUVp0bDAyTS9Nd2RBQjdZ
            TlVpZmcreVZPTlE2RVB1TllzUDAvbFRSUUNVCjVkZ3hobTVsajM5N0duZWVmVndG
            T3c2dm4vNWlqejYxYUxCUUkvbzFNQVUKLS0tIEttdkNzYVpiUHg1RmdobzhhbGsv
            dlJlaDY2eUR0V0gvZE5CZWY4M3hSWWMK8KhprSh+RDTU3o+rFG8L90/sExFfsonu
            l1kELUcyjdatb1efAmB73XnbHao2jKDyVsajih0nYEH+2gwR3NWgdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13y3kv3ees7xx8fkerfcvjk0sjaz0n6f5pztu6ply4gl2tfhdjulstj4d2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOVlwNlFlcjVUVWdqUjFW
            c3FPWFFMbXVCeURSQlgvWUFLMDRBaUxnQVJNCm9xUitOZUNPR0s5Y1NtdE1aK24x
            aDhXbmYwcjE0OEZCenhtK3RMUjFrUm8KLS0tIEl6MEhndzZuSE5OT0pyRkRPOHdI
            MzA3ZzdQMnFCTGdEdVdEYkMrdlQ3S0UK2dgckNILNa1bQKScQ5eNwgoRjBcK3fCG
            Mmk6hQ1cEVPXSETxU+tnmgbNt+zTuJ8wZtH09IoTmEUYzHGBvmOGqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19w9wmdra2frq9f7hv0883xprnzzgfulv29fru25wgyfgwuxt6yjqnsvg04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMlExanJ4Yk5wVTltNmNH
            eXU4dWxmdHExOGdpTVI5VzRlVC9HOWN5ZHhjCmErRmwwRHhYaHJReU93YkVCa1hJ
            YTRlNlVwbURaV3B5SzQyd1VORXhodncKLS0tIE9uVWtLd1BRN21ERmJZNGl0NVB3
            WS80ZEM3QWloOC9MdHczNVBGVXVYbEkKT4e+wqpmfY5Sz6n/eXLvC7JQLbADAS09
            l2za60uupq9Jt80Z6GttjacQoBGZk+KlK1cNG4y3a18TgHjbO0vpZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T18:13:53Z"
    mac: ENC[AES256_GCM,data:klktqmy5OP1+wZMRIpchJ1tjcGPETONGYX1I5TgfnL9GS4ocUxNk2RV79uIZeLtHVejIm+DvkfURkjo51NCgukabR/w8WKOUxarq6acPiO1/mODgMbXUqwv/tNgDXHl56A8qNlphiWHIAkiMC4FcpB+75BKIRkmRVRMU6+9baQc=,iv:wCkv1+xNz1N9PyZ7cxD3iYjOMxldmzPbLA8TBtaQU1U=,tag:XjOHPozdTN5sYPoa/jyRNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
