users:
    hashed-root-pass: ENC[AES256_GCM,data:ZVcYKK1RpPtIn8ewuKUHI2LtknxnkC8G4Hiawg34XmxbpPOWhgmA9i9S304mVng9qLeYYmWyLu9leAzRJ8nim5jSnXGsakvO1w==,iv:1z1FlpL2ix7RJXpg2kTLkI0VKeg3Bl4cY5ScL48O6Q8=,tag:sTHkTxWKDcQuVA3ppCIKfw==,type:str]
    hashed-user-pass: ENC[AES256_GCM,data:dYkXzNgHT6Xq/pJE06Lz1222tTFcclKhWAjI8ZmhTBggaFmIc00XRwednCjc0GFU/vJdQGv1FC10hmJdODaAMHQsWV6cvGCRsw==,iv:KGYmJM2rg7tSyKhYGSrFIkfU1xA5wyib58jYMlMe43I=,tag:GLsRcH8QX+XHKSH99O4lVA==,type:str]
eduroam:
    id: ENC[AES256_GCM,data:7c7VPT10cIJXlTH3aEkC4A3sBD4=,iv:snuGbgIsPSTsI4IRulqnOmEu0p17OeO+zCm/s8JoP9g=,tag:KEKUU4lXRZlhlFmUKvy0aQ==,type:str]
    pass: ENC[AES256_GCM,data:nOaEBYssFZp2aw5H3kg=,iv:gFbd2ZlZ2dy2srqjh+AbRSgzJV5GndWHjR0ThAawtJw=,tag:oRqiwnJSNYPtmQvPq5EW1w==,type:str]
zyxel:
    pass: ENC[AES256_GCM,data:pQGQvtOem41CzA==,iv:q9RaHgcCGSnsnfXxCYvD10N5fXG6nZZBHIDlDDKnOl0=,tag:LOMYU7IDU9nHw4dTc1wNxg==,type:str]
github-pat: ENC[AES256_GCM,data:tKNGtRHCaNtvLNfhoml4KxyynZOA5FUtG4bDrK2sfRD1T25f8HA1M3OXi0RNT3YielZRi5O1BMZVAysTZJS2aj8GPZHB42a2P7MgCD7kYrcoJaVlKgLwY0HA0ENF,iv:geJWsDBhtxP4Bt6610bOikA7d+pkerQj9789nyzs2ec=,tag:1IzVN6eAGt57YvEyKkZH3Q==,type:str]
nix-signing-key: ENC[AES256_GCM,data:Y6yKcFdrMCQvcnxkeLQEn7E/51un77LxwpIWVQqT+q6nSlnPNYsmw/xDTzon+4LgKOJCvbtIyBZfeVsvWUzFN+DEPkFrpu1lnQkdcOlDF+rYF/c9EecUVw91blEKQ6ND,iv:SEpr7qxSkJVpusti5+4MZr20aLPMxkQKa/aoH5HIFLw=,tag:ncR/fpNlqfD11d8wa+KiZQ==,type:str]
attic-netrc-file: ENC[AES256_GCM,data:CisvY2/eycpwnmbhhPX+8f2ZsRkgyqqgc3Tb20UNN/6VsIFEy3cDWyFkcUKz6knTpkVRnmjdWGKQZXx0wke6lx1mUlM125QbSLMaGjlvXRoTbt4cRIlPgnC3BZFCXv217kTYdU8QMkW4SXS/DilE4FXAxqCXkwY0K1RhGKhr3YYpmP/fzicDT2f7WHXx2KpDJuHvbK6PyN5XJbPaniCr2esSNgpcZyAFIGB/xHG3++pi6Gr4x2eF4iR3W9hCNlGkI07YpFUC4IfW9yWA9AnY/XcinaGRs6zfE4ycKkquWjfIJoESV9+bzb7LjEFBIKewFi9BFZALL6pb1lYc8BVjKRhIuf3prV27RStQjaXzUlJy66c6hmBUMkVSrjgDzYRyM+XEMfY6Ml9VXhgnODOw3pekDd0kFWMcwl9EyuwxHvE9JI26Uh2BuxcXDr3GPKLrYpK5NP3TmxtV4hXAW0qOwtiTVQa1kfPsjflCUgCC/Om0xmYgiLI8Bqrw4OuBe43gFr+rCDJ6DaRAaPnXr8WhnTohUz7A1+ZOkc/IZ6GiIjfdr7ltZwnU1jEVJrjaa1Kkuszj7t+zevWiqvFzYb5uA9MtyZVk04MXeYt5255w68pNyUQolUQ0Se2ZiTdSs1TuSfTjj84qY6FKITj+xnq9qaKDZgREthKxAFCjNzUsgFmnaDlbpCka3lcHbBgCZvwbVIHvn20D2cYWiGbVTdy6kCAZcDlhbbi1B2Uk1JYPb9SvGEyU1FN2khtz+XT8IMoB/jctW6e15cq4n70c5nWS3TzRuZ9EytsxhtXcemxxOkm4qtpovCnZZY7LI3qKMyI+7S/D9AktbjlO87HMzEGQXAG7P+EO04Rt+sq+4r12lF0go49qwaoLXZpDB5xXXmNZwMV82y6/rMmuu2JHVF582lMdhwsEF1h5rN/3N6bOuPHr8tzEGE1a0lzqEOVuo4xYAuyW2K036hX7nRqUMiO0Uo+lpqZ772Sq2rLEXtJPW5k9txgOoJGndGyygYHhxs8xuUO/8lX6Jzi4vgj0Nqoc6S2Ua0hFm/NA8TDqlKiUI4N/ZdNGnDd8jxgyjsKizkOjQScJfsz4EtmpZwuKt8aL1h+lpzfEl24sktUJPs9LYPKiEbjZRJPlUqVpT5oPgHJLU3IEvLZzqNN4giv2/SmZri6T3Dc5MY915MRVfgegdMElR17pFyqiDvTD7meeQtP632zNqyYvzi5WCwerw0Fp,iv:o8s3v9oTlfmRBTQC16nW4r3LGgpsSgtwp6O9+9Ne0ck=,tag:tiecL7nfvm8VzfYECYRFUA==,type:str]
sops:
    age:
        - recipient: age1gwpmfgjkhcwp8nlaljxfdr3pp0np02656eq9kjpmtt0u3al99smswuj8lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVW9NbW51dlljTW9paDZV
            Q0hWQ1VMSUFuZk1JdFd6YkN6OWZxTFFPdkhnCis1ZjNXRlVPR1V1MmpIR1Job0tF
            THl2S0Q4M3Y3bkQybi9vUi9KaGx5M1EKLS0tIDN5M0tIQ05RSFFiZHAvSnFlUnFN
            VVh4TndnakZCSjE3Z2JENHdYenRFcFUKbdNZH0BsE/NuhGl+R0DEcwXTmj4vwHie
            AZ9CUO8aT6mmF//BksSuvJ7+2GBVkPeSuyCE6aibuXWIZAJplbSUIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13y3kv3ees7xx8fkerfcvjk0sjaz0n6f5pztu6ply4gl2tfhdjulstj4d2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTHc1TVVBa1VmcVpPTk1n
            VG4xbmRPNWgybjFjd0lMbTRtVnpiUEtzcnhZClpIcmlPT2pSbm5GWm4zZGlzRERy
            RU5qamhWcHVMUnV2VlIvcUd5bUlzQm8KLS0tIE90a2tFY2htT1d5NDVvOERFU3ZO
            RUhnOE1FNkcxWWg0dGVIWE80a0dVVlEKY1/+KET02/+4XhWo93Ww5GPaSt5arCsP
            2BBuny3+Rp9zpc1BncRQ9P+F3FJ7dTJTRzo+qM/t5FqsxZIBh+OVTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19w9wmdra2frq9f7hv0883xprnzzgfulv29fru25wgyfgwuxt6yjqnsvg04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWTZVUi9XcmdwZGhnUFBv
            VUhEWGJIRFNQbVVSOU9yWWJTR1VGOHg0L1ZvClo5MDVuSDlJdlphdDVWK3haVGJM
            QUQ2elVFeGYvMHNhdUtic05GcFliYmsKLS0tIGVJelM3OWwzREZ1bmNFS2RjQ1ZI
            bVdJRWhyS1oxUEI3KzNzRlpmc09QMlkK1En78AnBxU2Lts7v7MLAzrQtYv90GFyR
            1MYOd8jD5GSqtzLiTGuA3MlrnCNML/XqmV7Ye67S62WJuy4raRzQbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1urqqvjhryzm742tmt6yrzxp6g7h45r4mnz4fdfx0r4d7ygspd5uqelpzh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrelh2SzZPaC96NitBT0Iv
            cmY2ZEZreGpKajY3ZVRhbmx6MDVqY3FMWXl3CnhtMlRTbmRyRVJaZXIxU24xRE5j
            TXBBS3JwQmFSWUJRUjVnZGFucG84WVUKLS0tIFR6NjNFNGdia1B6ODRjSkU1VjAx
            VUUzZGhhOWNuTkE3KzBwWkNsazVFbTQKCWlhvswx0IMI0pYhP2ATDJdZgPMOTZAd
            dL7yzBqqQlx5VaN49LPdxQDrP84z4WN6orJq5wSsG2RStZqcmV4Ceg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T02:35:08Z"
    mac: ENC[AES256_GCM,data:Gr5LA9O/Vom0dlniGIQ+rYCfXd4dbNMQVFOPRT1WyPxzNqhdsQ47Gdnj42K9vmfn6UybnS92bOAc0ZeQMu43tcE6Wll0ECE18ri5q0VcVFp3nBv1vOtX9Ord//SF34pPHF2vTm9GYA9+q3PHcKmEAL3ZR+rKTy9pzA1rLADbX4U=,iv:p4wTMOnjNeiywkDL8w6XVhNdiZPkNWsxHYW4no/WMeU=,tag:X4OQQJi2OxSKC1cDfdcw9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
