cloudflare-api-token: ENC[AES256_GCM,data:MlJLjFGPXxoWNF2uJ3w8naDHALEz9yJS8t4NI58XPgCTCjONc5//cXn3BIQspCcGvUI9h7E=,iv:a2UviBhMSvHJ08XHeJHRxFrXrjtHfW47RJBcgaIZ/G0=,tag:R5N5XNgf3qY+P0SKY6Ytlg==,type:str]
sops:
    age:
        - recipient: age13y3kv3ees7xx8fkerfcvjk0sjaz0n6f5pztu6ply4gl2tfhdjulstj4d2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTGNQTWRWYlRWcThYd0Fn
            djFINVZBbC9ndlkyT3RDbis4YWc2a1U2QlJZCnJNdzNQam1lZktrRXdMby9GZXJi
            NktlRkNyQzhEK2VtdUh6dkpxOGc4bGsKLS0tIDBlS1k1Q2N1TlZic1k1aFEvNHRm
            bG9Tb3J2YTZFSnkyQTZMOUR5cEt2OWMK3fCjOUGaPNdMAYbPPWk/qQMu8mJxVI1C
            dKJuaENgkxnpLBgKkfVk0N8hsTQue8ReMaJ6aHvEikNHAd1a1CinIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1urqqvjhryzm742tmt6yrzxp6g7h45r4mnz4fdfx0r4d7ygspd5uqelpzh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RC9mV0dTbFBHait4Mmlx
            QURrT2MxcWtBS0xESXJEWk5YeVIwM2dmMmt3CnNHSFNmbXhoOGNLODd6MjdpVnRI
            eTJ3Rng4eEdudDJkdEtXeHpUVUVhK1EKLS0tIEROaWtZUkNHc2trbExiWlNPcjEr
            UFMyYVR4WUdQV0p5VnRZMTlaWmJwUFkKxPPtP/UoWC4tx5d/oQBIHXhnBmx+dP2P
            EJvmv6XR6auXqJC7OxWg2SsbzkorE9yLjJJEIAFicMFDJJZZZ2KcMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T23:45:03Z"
    mac: ENC[AES256_GCM,data:gdhTRb00Bng4uZlzXFha+080XtR7Y6D580Y8FIGfxOvGUuGRnwtLcZqa2AfiutZW43GSR1dUrvMtqvuuAFvk6jbRVi/JdSZQpLOfcJvyR1WOOlfl5rMrCUIxVvKNcn0nJPGR67iS3F1kfvHkI2UwrYzn/u4m24QhmCtR1SYo69Y=,iv:oiBTBJtpbMyjzuKmRBPinlkc2zgVG0k62LNd+C3xL6Q=,tag:HtPweITwYgLb6E0U/Xl0Mg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
