name: Build & Cache NixOS configurations
on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''
concurrency:
  group: build-and-cache-${{ github.sha }}
  cancel-in-progress: true
jobs:
  generate_matrix:
    outputs:
      configs: ${{ steps.generate_matrix.outputs.configs }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
      - uses: cachix/install-nix-action@v31
      - name: Configure attic
        run: |
          nix profile add --impure --expr \
            "(builtins.getFlake (toString ./.)).inputs.nixpkgs.legacyPackages.$(uname -m)-linux.attic-client"
          attic login main https://cache.gorilla.gay "${{ secrets.ATTIC_TOKEN }}"
          attic use main

      # only puts configs that were not already cached into the matrix
      - name: Generate matrix of non-cached configs
        id: generate_matrix
        run: |
          nixosConfigs=$(
              nix eval .#nixosConfigurations \
                  --apply '
                    attrs:
                    builtins.concatStringsSep "\n" (
                      map (name: "${name} ${attrs.${name}.config.system.build.toplevel.outPath}") (
                        builtins.attrNames attrs
                      )
                    )
                  ' \
                  --raw
          )

          configs_json="[]"
          while read -r config outpath || [[ -n "$config" && -n "$outpath" ]]; do
              nix path-info --store https://cache.gorilla.gay/main "$outpath" >/dev/null && continue
              configs_json=$(jq -c --arg v "$config" '. += [$v]' <<< "$configs_json")
          done <<< "$nixosConfigs"

          echo "configs=$configs_json" >> "$GITHUB_OUTPUT"

  build_configs:
    needs: generate_matrix
    # skip job completely if all configs were cached
    if: fromJson(needs.generate_matrix.outputs.configs)[0] != null
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.generate_matrix.outputs.configs) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - uses: cachix/install-nix-action@v31
      - name: Configure attic
        run: |
          nix profile add --impure --expr \
            "(builtins.getFlake (toString ./.)).inputs.nixpkgs.legacyPackages.$(uname -m)-linux.attic-client"
          attic login main https://cache.gorilla.gay "${{ secrets.ATTIC_TOKEN }}"
          attic use main
      - name: Build config
        run: |
          nix build .#nixosConfigurations."${{ matrix.config }}".config.system.build.toplevel
      - name: Push to attic
        run: |
          attic push main result
