# Inspiration from:
# https://github.com/NobbZ/nixos-config/tree/main/.github/workflows/flake-update.yml
# https://github.com/lajp/nix/tree/main/.github/workflows
name: Update & Build NixOS configurations
on:
  schedule:
    - cron: 0 3 * * 1,4
      timezone: "Europe/Helsinki"
  workflow_dispatch:
concurrency:
  group: flake-update
  cancel-in-progress: true
env:
  BRANCH: &branch "ci/update-flake"
jobs:
  update_flake:
    outputs:
      update_available: ${{ steps.output.outputs.update_available }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Update flake
        id: update
        run: |
          git checkout -B "$BRANCH" "origin/master"
          nix flake update \
            --commit-lock-file \
            --option commit-lockfile-summary 'ci: automatic flake update' \

      - name: Output & push
        id: output
        run: |
          if ! git diff --quiet --exit-code "origin/master"; then
            echo "update_available=true" >> "$GITHUB_OUTPUT"
            git push --force --set-upstream origin "$BRANCH"
          else
            echo "update_available=false" >> "$GITHUB_OUTPUT"
          fi

  build_and_cache:
    if: ${{ needs.update_flake.outputs.update_available == 'true' }}
    needs: update_flake
    uses: ./.github/workflows/build-and-cache.yml
    with:
      ref: *branch
    secrets: inherit

  create_pr:
    needs: build_and_cache
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: *branch
          fetch-depth: 0
      - name: Create and merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR=$(gh pr create \
            --base master \
            --fill \
            --label bot \
            --title "Auto flake update $(date -Idate)")

          gh pr merge "$PR" --rebase --delete-branch
